config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root 'welcome#index'

  resources :scores
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :published_at, scope: %i[user_id]

  self.table_name = "nytimes_mini_xword_results"

  def published_day
    published_at.in_time_zone("America/Los_Angeles").strftime("%b %e %Y")
  end

  def published_time
    published_at.in_time_zone("America/Los_Angeles").strftime("%l:%M:%S %p")
  end
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :published_at, scope: %i[user_id]

  self.table_name = "nytimes_mini_xword_scores"

  def published_day
    published_at.in_time_zone("America/Los_Angeles").strftime("%b %e %Y")
  end

  def published_time
    published_at.in_time_zone("America/Los_Angeles").strftime("%l:%M:%S %p")
  end

  def to_json
    {
      username: user.name,
      seconds: seconds,
      published_at: published_at,
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :nytimes_mini_xword_results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  SCORES_SECRET = ENV["SCORES_SECRET"]

  private
    def authenticate
      return if Rails.env.development?

      authenticate_or_request_with_http_token do |token, options|
        begin
          JWT.decode token, SCORES_SECRET, true, { algorithm: 'HS256' }
        rescue JWT::DecodeError
          false
        end
      end
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  protect_from_forgery with: :null_session, only: [ :create ] 
  wrap_parameters Score, include: [ :username ], format: [:json], only: [ :create ]

  before_action :authenticate, only: [ :create ]

  def index
    @scores_by_date = {} 

    Score.all.each do |r|
      date = r.published_day

      unless @scores_by_date[date].present? 
        @scores_by_date[date] = [] 
      end 

      @scores_by_date[date].push(r)
    end
  end

  def create 
    scores = []
    created_new_records = false

    byebug
    params[:_json].each do |p|
      require_params(p)
      user = User.find_or_create_by!(name: p[:username])
      score = Score.find_or_create_by!(user: user, seconds: p[:seconds], published_at: p[:published_at])
      unless created_new_records
        created_new_records = score.previously_new_record?
      end

      scores.push(score.to_json)
    rescue ActionController::ParameterMissing => e 
      render json: { message: e.message }, :status => :bad_request and return
    end

    render json: scores, status: created_new_records ? :created : :ok
  end

  private

  def require_params(p)
    p.require([:username, :seconds, :published_at])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate, except: [ :index ]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StatsWithFriends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/index.html.erb
<% @scores_by_date.each do |date,scores| %>
  <p> <%= date %> </p>

  <ul>
    <% scores.each do |score| %>
        <li><%= score.user.name %> <%= score.seconds %>s at <%= score.published_time %> </li>
    <% end %>
  </ul>

<% end %>

app/views/welcome/index.html.erb
<h2>Stats, with Friends (Riley Edition) </h2>

<p> <%= link_to "NYTimes Mini Crossword Scores", scores_path %> </p>

<p> <%= link_to "Swagger API Docs", '/api-docs' %> </p>